name: equbapp
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Versioning for the app
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons for iOS style icons
  cupertino_icons: ^1.0.6

  # Firebase dependencies
  firebase_auth: ^5.5.0
  firebase_core: ^3.9.0
  firebase_data_connect: ^0.1.2+5

  # State management using flutter_bloc
  flutter_bloc: ^9.0.0

  # For show/hide password functionality
  show_hide_password: ^0.0.2

  # Secure storage for sensitive data
  flutter_secure_storage: ^9.2.4

  file_picker: ^9.0.0
  http: ^1.3.0
  mime: ^2.0.0
  http_parser: ^4.0.0
  url_launcher: ^6.1.14
  image_picker: ^1.1.2
  webview_flutter: ^4.10.0 
  camera: ^0.10.0+1
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Equatable package for value comparison and equality
  equatable: ^2.0.3

  # Linting rules for clean code
  flutter_lints: ^3.0.0

flutter:
  # Ensures the Material Design Icons are available for your app
  uses-material-design: true
  assets:
    - assets/images/image1.png
  # Fonts configuration for custom fonts in your app
  fonts:
    - family: Heading
      fonts:
        - asset: assets/fonts/RobotoSerif-SemiBold.ttf
        
    - family: Body
      fonts:
        - asset: assets/fonts/RobotoSerif-Regular.ttf

    - family: DefaultFont
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

  # Assets configuration (currently none, but can be added in the future)
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

