// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgjC9JxLVR8P-9ai3Mgp5T9-a2tRzxWOU',
    appId: '1:82455720123:web:15e4c2e19a180b11f7399e',
    messagingSenderId: '82455720123',
    projectId: 'equb-6a176',
    authDomain: 'equb-6a176.firebaseapp.com',
    storageBucket: 'equb-6a176.firebasestorage.app',
    measurementId: 'G-H2LPFB8ZK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB60OqEAdYgJIfuuvAc_Ny9ScHcJwTWV2k',
    appId: '1:82455720123:android:4b18897fb45020f4f7399e',
    messagingSenderId: '82455720123',
    projectId: 'equb-6a176',
    storageBucket: 'equb-6a176.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBANifko5RZ6ewJt4kEqvY2_k8T_2LvlMU',
    appId: '1:82455720123:ios:3371628bddda63dbf7399e',
    messagingSenderId: '82455720123',
    projectId: 'equb-6a176',
    storageBucket: 'equb-6a176.firebasestorage.app',
    iosBundleId: 'com.example.equbapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBANifko5RZ6ewJt4kEqvY2_k8T_2LvlMU',
    appId: '1:82455720123:ios:3371628bddda63dbf7399e',
    messagingSenderId: '82455720123',
    projectId: 'equb-6a176',
    storageBucket: 'equb-6a176.firebasestorage.app',
    iosBundleId: 'com.example.equbapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgjC9JxLVR8P-9ai3Mgp5T9-a2tRzxWOU',
    appId: '1:82455720123:web:7e98e3c607d1221ef7399e',
    messagingSenderId: '82455720123',
    projectId: 'equb-6a176',
    authDomain: 'equb-6a176.firebaseapp.com',
    storageBucket: 'equb-6a176.firebasestorage.app',
    measurementId: 'G-TSZ8H9D17H',
  );
}
